site_name: Rafael Dias | Knowledge Base
site_description: Artigos sobre Python, Django, arquitetura, cloud e engenharia de software
site_author: Rafael Dias
site_url: https://rafaelmcddev.github.io

repo_name: rafaelmcddev/rafaelmcddev.github.io
repo_url: https://github.com/rafaelmcddev/rafaelmcddev.github.io
edit_uri: edit/main/docs/

hooks:
  - hooks/gerar_conteudos.py

theme:
  name: material
  language: pt-BR

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Ativar modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Ativar modo claro

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search:
      lang: pt

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables

  - toc:
      permalink: true
      title: Nesta página

  - pymdownx.details

  - pymdownx.superfences

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.inlinehilite

  - pymdownx.snippets

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Início: index.md
  - Conteúdos: conteudos.md
  - Sobre: sobre.md


extra_css:
  - assets/stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rafaelmcddev
      name: Rafael Dias no GitHub

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rafael-dias-64016023/
      name: Rafael Dias no LinkedIn

copyright: >
  Copyright &copy; 2026 Rafael Dias